// Bundles src/ into ONE self-contained index.html (CSS + JS inlined) so it works in any previewer,
// from file://, or from a single uploaded file. Run: node build.js
const fs = require('fs');
const path = require('path');
const SRC = path.join(__dirname, 'src');
let html = fs.readFileSync(path.join(SRC, 'index.src.html'), 'utf8');
html = html.replace(/<link rel="stylesheet" href="([^"]+)">/g, (_, f) => '<style>\n' + fs.readFileSync(path.join(SRC, f), 'utf8') + '\n</style>');
html = html.replace(/<script src="([^"]+)"><\/script>/g, (_, f) => '<script>\n' + fs.readFileSync(path.join(SRC, f), 'utf8').replace(/<\/script/gi, '<\\/script') + '\n</script>');
fs.writeFileSync(path.join(__dirname, 'index.html'), '<!-- GENERATED by build.js from src/ -- edit the files in src/, then run: node build.js -->\n' + html);
console.log('built index.html', (html.length / 1024).toFixed(0) + ' KB');
